### ISSUE TITLE
PPOD Title List with Status and Amount Paid

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#10]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

Contains list of titles associated with the Print Purchase on Demand workflow. Includes discovery records, and purchased titles with amount paid. 

Filter by fiscal year, status (discovery/paid). 

[Acquisitions Workflow](https://docs.google.com/document/d/1YVGjX7fMWf6Qs_pQ8viSZkjHYksYpiEHejXfw6OzLC4/edit) 

[MODS Workflow](https://o365coloradoedu.sharepoint.com/:w:/r/sites/LIB-RDServices/_layouts/15/doc2.aspx?sourcedoc=%7B16CDFB65-F2EC-4E97-8A4C-F99BF2B31C66%7D&file=Print%20DDA%20discovery%20records.docx&action=default&mobileredirect=true&cid=38b71924-7688-4f10-a39e-75623a9daf6d) 

STAKEHOLDERS: 
Financial/Accounting: Juleah Swanson, Kimberly Lawler, Rebecca Stone
Receiving: Leo Arellano
Assessment: Gabrielle Wiersma, Arthur Aguilera

**Comment by rebeccacolaw** [comment]
In Sierra, these have order type = "w"

**Comment by rebeccacolaw** [comment]
12/8: RC was unable to find a place where "w" was recorded. The options for Acquisitions methods are as follows:


![Image](https://user-images.githubusercontent.com/83369766/206524077-c0927769-8f63-4df1-af66-af8a9665151f.png)

**Comment by arthur-aguilera** [comment]
Replaced by #76
