### ISSUE TITLE
ACRL Collection Statistics

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#12]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

This query produces the numbers needed to complete the annual ACRL Survey. Survey instructions: https://drive.google.com/file/d/1IRr7ah2oP31Rkq0jsTFDhv_MszQbo_PE/view

There may be a need to make slight modifications if the instructions are revised. The most recent instructions and definitions document should be consulted. 

[ACRL Collection Statistics Workbook](https://docs.google.com/spreadsheets/d/1ZmRTqmBw_k0zoEDOLN-O6q6op7TH4TrSGyWeE2ZIPaY/edit#gid=1241634129)

**Comment by blocke1** [comment]
Title count by fiscal year canned report from Cornell (counting bibs):
https://github.com/cul-it/cul-folio-analytics/commit/3d4ff344b45c914574be46a92efa7778574b96df

**Comment by arthur-aguilera** [comment]
Replaced by #78
