### ISSUE TITLE
Gemmill Claims Returned Report

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#120]

**Comment by AmeliaDS** [comment]
--Returns a list of all items marked 'Claimed returned' across selected Engineering, Math, Physics Library locations.
SELECT DISTINCT
	lt.item_status AS status,
	lt.claimed_returned_date AS claim_date,
	it.barcode AS barcode,
	lt2.name AS location,
	hrt.call_number AS call_number,
	it.copy_number AS copy_number,
	it.volume AS volume,
	it2.title AS title,
	lt.action_comment AS note,
	lt.user_id AS patron_uuid
FROM folio_circulation.loan__t__ lt 
LEFT JOIN folio_inventory.item__t__ it ON it.id = lt.item_id
LEFT JOIN folio_inventory.location__t__ lt2 ON lt2.id = lt.item_effective_location_id_at_check_out
LEFT JOIN folio_inventory.holdings_record__t__ hrt ON hrt.id = it.holdings_record_id
LEFT JOIN folio_inventory.instance__t__ it2 ON it2.id = hrt.instance_id
WHERE lt.item_status = 'Claimed returned'
	AND lt2.code IN ('ENG','ENGRES','ENGOV','ENGPOP','ENGST', 'ENGPS','ENGMC','ENGOS')
	AND call_number IS NOT NULL
ORDER BY claim_date
;

/*Results & Questions:
-Ran and returned 2 items (9/15/23) 
*/
