### ISSUE TITLE
ILL Print Purchase on Demand

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#15]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

Running lists of orders placed on ILL POD to track the budget for zpdmo (Borrowing)

Limited to purchases with the fund code zpdmo

STAKEHOLDERS: 
Beth Arellano
Juleah Swanson
Gabrielle Wiersma
Arthur Aguilera
Rebecca Stone

Wiki Page: [ILL Print Purchase on Demand](./ILL-Print-Purchase-on-Demand)

**Comment by libraryfemme** [comment]
@arthur-aguilera @JuleahS  I had a list in Sierra for this purpose but it appears it's been deleted. Therefore, I'll need some help from Acquisitions to recreate the POD orders list. Basically it was just fund = zpdmo, but I know there were additional parameters that Steve Selleck helped me to create and for which I don't have a record of.

**Comment by arthur-aguilera** [comment]
Closing since this will now be covered by #76
