### ISSUE TITLE
New Titles List

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#17]
Users can search for new titles in the Inventory app by using the **Date created** filter. 

- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Create SQL Custom Report (if needed)
- [ ] Have SQL Custom Report Reviewed (if needed)
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

FILTER BY
Location, Fund, Year, 

INCLUDE
Title, ISBN, Location, link to record

STAKEHOLDERS
Gabby Wiersma, Liaisons, Communiciations

**Comment by steveellis** [comment]
Could be addressable from Inventory app. There is a `date created` filter and a `date updated` one.

**Comment by arthur-aguilera** [comment]
Replaced by #77
