### ISSUE TITLE
Circulation Activity Report

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#18]
Circulation Activity Report - [Wiki Page](https://github.com/culibraries/library-reporting/wiki/Circulation-Activity-Report)

[About FOLIO Reporting Dashboards](https://docs.google.com/document/d/1Jmz-MGcYE2RSimpiSBzBdbdixICjWkqMwxk7wdglZhI/edit#)

- [x] Create Wiki Page for Report
- [x] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [x] Identify Fields Needed for Report
- [x] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [x] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Port [loans_items.sql](https://github.com/folio-org/folio-analytics/blob/main/sql/derived_tables/loans_items.sql) to MetaDB
- [ ] Review Query
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

A dashboard summarizing loan activity. 

- [ ] Loan Activity by Location: loan activity by location, building
- [ ] Loan Activity by Item Type: loan activity by item material type and/or holdings formats
- [ ] Loan Activity by language: loan activity by language code name
- [ ] Loan Activity by Classifications: loan activity by LC subjects (see #81)

**Comment by steveellis** [comment]
@curtdwilliams this seems like it would be in your area maybe.

**Comment by arthur-aguilera** [comment]
On hold until Resource Access is able to test the Circulation Log, Check In and Check out apps. Currently no metaDB data available in our instance or MetaDB test instance.
