### ISSUE TITLE
Patrons That Have Items

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#19]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

Can be pulled by Patron Type, Item Type, Item Location. Includes: number of patrons, number of patrons w/items, % w/items, number of items, avg/patron, number overdue, number with fines, total fines

**Comment by steveellis** [comment]
Probably a starting point here: https://github.com/folio-org/folio-analytics/tree/main/sql/report_queries/patron_list at least for the patron part. Seems like it needs to join the items though.

**Comment by steveellis** [comment]
Also https://github.com/folio-org/folio-analytics/tree/main/sql/report_queries/overdue_items which has columns for patron info and overdue items. So could be refactored to contain just patrons who have items.

**Comment by arthur-aguilera** [comment]
Closing because this is really not needed. What we need is a patron activity report which can be part of the Circulation Activity dashboard
