### ISSUE TITLE
Orders Records with Paid Status

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#20]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

Wiki Page: [Paid Orders](./Paid-Orders)
Used for reconcillation, budgeting, expense tracking

FILTER by paid date, fiscal year

STAKEHOLDERS
Juleah Swanson
Gabrielle Wiersma
Kimberly Lawler
Linda Helgoth
Rebecca Stone

See Cornell's Report: https://github.com/cul-it/cul-folio-analytics/tree/main/canned_reports/CR101 
https://github.com/cul-it/cul-folio-analytics/tree/main/canned_reports/CR109  - Standing Orders?

**Comment by steveellis** [comment]
Related: https://github.com/folio-org/folio-analytics/tree/main/sql/report_queries/orders. But also there is a very robust orders app: https://folio-snapshot.dev.folio.org/orders so could very well be handled by an In App report. @arthur-aguilera @JuleahS can we consider this done?

There are six checkboxes for different payment statuses in the app.

@JuleahS let us know what you think.

**Comment by arthur-aguilera** [comment]
Closing since requirements can be meet within the Orders App, and export options are covered by #76
