### ISSUE TITLE
Open Orders

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#22]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

Report on orders with status code "o"/[or open] for unpaid one-time purchase

STAKEHOLDERS:
Juleah Swanson
Rebecca Stone

Wiki: [Open Orders Report](./Open-Orders-Report)

**Comment by steveellis** [comment]
There is the orders report in folio-analytics: https://github.com/folio-org/folio-analytics/tree/main/sql/report_queries/orders

**Comment by arthur-aguilera** [comment]
Closing since requirements will now be part of #76
