### ISSUE TITLE
Trace lost and Missing Lists

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#26]
We are able to pull a list in the Inventory app, as well as export using an existing query that is an adapted to our needs. Wiki Page: https://github.com/culibraries/library-reporting/wiki/Missing-Books-Report

- [x] - [ ] Create Wiki Page for Report
- [x] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [x] Identify Fields Needed for Report
- [x] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [x] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

Used to reconcile status of items (a double or tripple check)

First status used to search is "m" for missing. 

Item status equal to L AND (Item location equal to norst or Item location equal to norov or item location equal to asnst or item location equal to asnov or item locaiton equal to scist or item locaiton equal to sciov or item location equal to artst or item location equal to artov); Update the first search to item status equal to trace for those lists

STAKEHOLDERS
Gabrielle Wiersma
Arthur Aguilera
Claire Hoag
Branch Managers

**Comment by steveellis** [comment]
Good starting point here: https://github.com/folio-org/folio-analytics/tree/main/sql/report_queries/missing_items.

**Comment by steveellis** [comment]
Also may be addressable from Inventory app: 
![image](https://user-images.githubusercontent.com/104455/155022426-5a18077d-4cf5-44d8-8eb4-f2c1c4bbcd56.png)

**Comment by blocke1** [comment]
Missing items canned report from Cornell (It seems like we should be able to use this):
https://github.com/cul-it/cul-folio-analytics/commit/721e5217ebf1f3311d090e268b52754601545ba4

**Comment by arthur-aguilera** [comment]
Replaced by #77
