### ISSUE TITLE
Google Book individual manifests

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#28]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

Used to create item list of individual google book trucks

ITEM  PATRON#  equal to  "p1803155" - replace the last number with whatever patron number you are working from

STAKEHOLDERS
Claire Hoag

Where will the icode1 project codes be mapped to?

**Comment by steveellis** [comment]
@curtdwilliams does your group handle creating these book trucks?
