### ISSUE TITLE
Collection Inventory Projects

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#29]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

Used for inventory projects to reflect current collection and reconcile statuses 

ITEM  IUSE3  greater than  "0"    AND ITEM  LOCATION  equal to  "norst"

STAKEHOLDERS
Claire Hoag

**Comment by steveellis** [comment]
Related: https://github.com/folio-org/folio-analytics/tree/main/sql/report_queries/shelf_list

**Comment by arthur-aguilera** [comment]
Replaced by #77
