### ISSUE TITLE
Item Count by Language Codes

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#30]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [x] Identify Fields Needed for Report
- [x] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [x] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [x] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

List of titles available by language. 

STAKEHOLDERS:
Adam Lisbon (requested Chinese, Japanese, Korean Counts https://docs.google.com/spreadsheets/d/1wCM__pZBjbC0udJNYJQ5ce5MKM5iO2cuNi9U_MQAWHw/edit#gid=1118679656)

You can get a list of instances and the assigned language by using the [instance_languages](https://github.com/folio-org/folio-analytics/blob/main/sql_metadb/derived_tables/instance_languages.sql) derived table.

**Comment by steveellis** [comment]
There is a title count query in FA: https://github.com/folio-org/folio-analytics/tree/main/sql/report_queries/title_count

**Comment by arthur-aguilera** [comment]
Replaced by #78
