### ISSUE TITLE
Backstage Record Pull

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#36]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

Records that don't have Cat Level: Local-Brief, Serials Solutions, Dataload, or Dataload/Pkg, and aren't suppressed or not supposed to go to Backstage, and have a Cat Date within a specified range (usually the previous month)

Monthly. To send newly cataloged records to Backstage for authority control

**Comment by blocke1** [comment]
Search string in Sierra:

BIBLIOGRAPHIC  CAT LEVEL  not equal to  "y"    AND BIBLIOGRAPHIC  CAT LEVEL  not equal to  "s"    AND BIBLIOGRAPHIC  CAT LEVEL  not equal to  "f"    AND BIBLIOGRAPHIC  CAT LEVEL  not equal to  "g"    AND BIBLIOGRAPHIC  BCODE3  not equal to  "n"    AND BIBLIOGRAPHIC  BCODE3  not equal to  "p"    AND BIBLIOGRAPHIC  CAT DATE  greater than or equal to  "[first day of the month]"    AND BIBLIOGRAPHIC  CAT DATE  less than or equal to  "[last day of the month]"

**Comment by steveellis** [comment]
It would be really really nice to be able map some of these Sierra fields to FOLIO fields. That would at least be a starting point.

**Comment by arthur-aguilera** [comment]
Explore if this functionality is covered in the Data Export app: https://wiki.folio.org/display/FOLIOtips/Data+Export
