### ISSUE TITLE
Backstage Records with 948 field added

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#37]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

Records that have a 948 bslw[fiscal year] : [month]

Monthly. This 948 is added whenever a record needs to be sent back to Backstage. These are records are added to the list of newly cataloged records for Backstage.

**Comment by blocke1** [comment]
Search string in Sierra: 

948 has bslw[fiscal year] : [month] (for example, 948 has bslw21/22 : jan)

**Comment by steveellis** [comment]
Should be doable once #55 is figured out.

**Comment by blocke1** [comment]
Used Monthly.

**Comment by blocke1** [comment]
From Emily Semenoff:
 2/27/2023:
“It turns out we can search admin notes in Inventory. So for the records with bslw22/23, I should be able to use Inventory to collect them, rather than a report from the LDP, since catalogers will be putting that note in admin notes in FOLIO.”
