### ISSUE TITLE
583 Colorado Alliance Retention Candidate Report

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#38]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

Monographs - Records that are monographs, are not suppressed, don't have a 583, are not microform or an electronic resource, and have an item in Pascal that isn't part of Gov, Special Collections, or Archives, and that doesn't have Onsite Only or Limited Use status.

Serials - Same as above, but for serials.

Semi-annual. This finds any monograph records eligible for the Colorado Alliance Shared Print initiative that aren't designated with a 583 yet.

**Comment by blocke1** [comment]
Search string in Sierra: 

BIBLIOGRAPHIC  ARL STATS  equal to  "m"    AND BIBLIOGRAPHIC  BCODE3  not equal to  "n"    AND ITEM  LOCATION  equal to  "pascu"    AND ITEM  ICODE2  not equal to  "g"    AND ITEM  ICODE2  not equal to  "!"    AND ITEM  ICODE2  not equal to  "h"    AND ITEM  STATUS  not equal to  "p"    AND ITEM  STATUS  not equal to  "v"    AND ITEM  I TYPE  not equal to  "6"    AND ITEM  I TYPE  not equal to  "39"    AND ITEM  I TYPE  not equal to  "53"    AND ITEM  I TYPE  not equal to  "15"    AND BIBLIOGRAPHIC  MARC Tag 049  All Fields don't have  "cod9"    AND BIBLIOGRAPHIC  MARC Tag 049  All Fields don't have  "cod8"    AND BIBLIOGRAPHIC  MARC Tag 245  All Fields don't have  "|h[microform]"    AND BIBLIOGRAPHIC  MARC Tag 337  All Fields don't have  "microform"    AND BIBLIOGRAPHIC  MARC Tag 245  All Fields don't have  "|h[electronic resource]"    AND BIBLIOGRAPHIC  MARC Tag 337  All Fields don't have  "computer"    AND BIBLIOGRAPHIC  MARC Tag 583  equal to  ""

**Comment by blocke1** [comment]
Search string in Sierra for 583 SERIALS:

BIBLIOGRAPHIC  ARL STATS  equal to  "s"    AND BIBLIOGRAPHIC  BCODE3  not equal to  "n"    AND ITEM  LOCATION  equal to  "pascu"    AND ITEM  ICODE2  not equal to  "g"    AND ITEM  ICODE2  not equal to  "!"    AND ITEM  ICODE2  not equal to  "h"    AND ITEM  STATUS  not equal to  "p"    AND ITEM  STATUS  not equal to  "v"    AND ITEM  I TYPE  not equal to  "6"    AND ITEM  I TYPE  not equal to  "39"    AND ITEM  I TYPE  not equal to  "53"    AND ITEM  I TYPE  not equal to  "15"    AND BIBLIOGRAPHIC  MARC Tag 049  All Fields don't have  "cod9"    AND BIBLIOGRAPHIC  MARC Tag 049  All Fields don't have  "cod8"    AND BIBLIOGRAPHIC  MARC Tag 245  All Fields don't have  "|h[microform]"    AND BIBLIOGRAPHIC  MARC Tag 337  All Fields don't have  "microform"    AND BIBLIOGRAPHIC  MARC Tag 245  All Fields don't have  "|h[electronic resource]"    AND BIBLIOGRAPHIC  MARC Tag 337  All Fields don't have  "computer"    AND BIBLIOGRAPHIC  MARC Tag 583  equal to  ""

**Comment by arthur-aguilera** [comment]
No longer needed as a query per Emily Semenoff and Erin Block.
