### ISSUE TITLE
Occam's Reader

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#39]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

All Springer records that aren't suppressed.

Semi-annual. To send eligible ebooks to Occam's Reader.

**Comment by blocke1** [comment]
Search string in Sierra:

BIBLIOGRAPHIC  MARC Tag 001  starts with  "spr"    AND BIBLIOGRAPHIC  BCODE3  not equal to  "n"

**Comment by steveellis** [comment]
@curtdwilliams or @ahlisbon this seems pretty straightforward. Bet it can be done with in app report. Added benefit: it has a fun name!
