### ISSUE TITLE
ERM Inventory Count from FOLIO Analytics

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#4]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

Canned Report: https://github.com/folio-org/folio-analytics/tree/main/sql_metadb/report_queries/erm/count

Also see: https://github.com/cul-it/cul-folio-analytics/tree/main/canned_reports/CR110

**Comment by arthur-aguilera** [comment]
@blocke1 Do you think this could be apart of #78 ?

**Comment by blocke1** [comment]
@arthur-aguilera possibly? I think I'm getting confused by the name change. There aren't "inventory" records for ERM.... so is this supposed to be a count of agreements? Or Inventory records?

**Comment by blocke1** [comment]
@arthur-aguilera if we're going for Inventory, I think it does look like it would be covered in #78

**Comment by arthur-aguilera** [comment]
@blocke1 oh! I think the link I had in the description for counting eresource records in inventory confused me (I guess some institutions do?) If this is only an agreement count, I still think it could be covered by #78?

**Comment by blocke1** [comment]
@arthur-aguilera I think so? Although I don't think we have a SQL query for Agreement count yet?

**Comment by blocke1** [comment]
@arthur-aguilera Sorry to answer a question with a question! : )

**Comment by arthur-aguilera** [comment]
There is a query for erm counts, but I think we could get counts for Agreements data here: https://app.powerbi.com/links/fEI7dmT_-O?ctid=3ded8b1b-070d-4629-82e4-c0b019f46057&pbi_source=linkShare&bookmarkGuid=cca800f3-2af1-49e3-83cb-0949f70b11d4 (after it's been cleaned up of course). So we could have a separate Agreements dashboard that will provide counts and data summaries (without a sql query) or we could also add this to the a general Collection Statistics Dashboard.
