### ISSUE TITLE
RAPID - Print monographs

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#42]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

All monographic records that aren't suppressed, are not in Special Collections or Archives, and have an attached item record.

Quarterly. To send print monograph records to RAPID.

**Comment by blocke1** [comment]
Search string in Sierra:

BIBLIOGRAPHIC  ARL STATS  equal to  "m"    AND BIBLIOGRAPHIC  BCODE3  not equal to  "n"    AND BIBLIOGRAPHIC  MARC Tag 337  has  "unmediated"    AND BIBLIOGRAPHIC  MARC Tag 338  has  "volume"    AND BIBLIOGRAPHIC  LOCATION  not equal to  "spc  "    AND BIBLIOGRAPHIC  LOCATION  not equal to  "arv  "    AND BIBLIOGRAPHIC  LINKED REC  exists to  ITEM

**Comment by steveellis** [comment]
Related #55.
