### ISSUE TITLE
RAPID - Print serials

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#43]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

All checking records that aren't suppressed, restricted, or part of Special Collections or Archives, and are attached to a serial bib records that also isn't suppressed or part of Serials Solutions.

Quarterly. To send print serials holdings to RAPID.

**Comment by blocke1** [comment]
Search string in Sierra:

CHECKIN  LOCATION  All Fields don't have  "spc  "    AND CHECKIN  LOCATION  All Fields don't have  "arv  "    AND CHECKIN  SCODE3  not equal to  "n"    AND CHECKIN  SCODE2  not equal to  "y"    AND CHECKIN  MARC Tag 863  not equal to  ""    AND BIBLIOGRAPHIC  BCODE3  not equal to  "n"    AND BIBLIOGRAPHIC  CAT LEVEL  not equal to  "s"    AND BIBLIOGRAPHIC  ARL STATS  equal to  "s"

**Comment by steveellis** [comment]
Related to #55.
