### ISSUE TITLE
Serials Solutions print holdings

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#44]
All serials records that aren't suppressed and have an attached checkin that also isn't suppressed and doesn't have the location "web."

Quarterly. To send print serial holdings to Serials Solutions.

**Comment by blocke1** [comment]
Search string in Sierra:

BIBLIOGRAPHIC  ARL STATS  equal to  "s"    AND CHECKIN  LOCATION  not equal to  "web  "    AND BIBLIOGRAPHIC  BCODE3  not equal to  "n"    AND CHECKIN  SCODE3  not equal to  "n"

**Comment by blocke1** [comment]
RDF: https://docs.google.com/document/d/15-VZUOlXRta0wyw5JSvH6DqIkF-IqSbD0bAGYB3d4rg/edit#

**Comment by blocke1** [comment]
It’s unknown whether this list will be necessary in the FOLIO/EBSCO environment. If our print holdings are entered/cataloged in FOLIO, and FOLIO and EBSCO holdings management and the EDS discovery system talk to each other, right now it seems like we will not need to manually update/send holdings.

**Comment by arthur-aguilera** [comment]
@blocke1 since serials solutions is gone, should we delete this issue?

**Comment by blocke1** [comment]
@arthur-aguilera Yes I think that makes sense! I think I just closed it instead of deleting the issue.... will try to figure that out now!
