### ISSUE TITLE
Holdings to OCLC

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#46]
- [ ] Create Wiki Page for Report
- [x] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [x] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [x] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [x] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

Any records cataloged in the last week that were not part of a dataload.

Weekly. To send new holdings to OCLC.

**Comment by blocke1** [comment]
Search string in Sierra:

BIBLIOGRAPHIC  CAT LEVEL  not equal to  "y"    AND BIBLIOGRAPHIC  CAT LEVEL  not equal to  "-"    AND BIBLIOGRAPHIC  CAT LEVEL  not equal to  "f"    AND BIBLIOGRAPHIC  CAT LEVEL  not equal to  "b"    AND BIBLIOGRAPHIC  CAT LEVEL  not equal to  "s"    AND BIBLIOGRAPHIC  CAT LEVEL  not equal to  "w"    AND BIBLIOGRAPHIC  CAT LEVEL  not equal to  "o"    AND BIBLIOGRAPHIC  CAT LEVEL  not equal to  "n"    AND BIBLIOGRAPHIC  CAT LEVEL  not equal to  "g"    AND BIBLIOGRAPHIC  CAT DATE  greater than  "02-11-2018"    AND BIBLIOGRAPHIC  CAT DATE  less than  "03-12-2018"

**Comment by blocke1** [comment]
RDF: https://docs.google.com/document/d/10wKsl6NLAEm80hK9hAAOSvBcltASU_E_utbGXjQ3TTw/edit#

**Comment by blocke1** [comment]
It is unclear where the fixed field in MARC records in Sierra that is needed for this report will end up in FOLIO Inventory records.  This report will need to be put on hold until we can get more information about the needed field in FOLIO. Or, we may need to create a new way to identify the records we need to send to OCLC. 

Chris Long and Emily Semenoff will be the people to contact about this as we move forward. 

Per Chris:

"It looks like for migrated records, the Sierra Cat Level code ends up in 998 $c. For records imported/created natively in FOLIO (i.e., non-migrated records), there isn’t an equivalent field in FOLIO. Cornell uses a text string to encode this type of info in an Administrative Note in Inventory, so I was thinking of doing something similar. I’m not sure where, or if, this data will end up in an exported record. We may need a new strategy to identify items needing OCLC holdings set – no idea at this point what that strategy might be."

**Comment by blocke1** [comment]
Per Emily, used WEEKLY. 
May be able to use Inventory and Data Export.

**Comment by blocke1** [comment]
WITH
field_998 AS (
SELECT srs_id, instance_id
FROM folio_source_record.marc__t
WHERE field = '998' AND sf = 'c' AND content NOT IN ('f', 'w', 's', 'y', '-', 'b', 'o', 'n', 'g')
),
field_994 AS (
SELECT srs_id
FROM folio_source_record.marc__t
WHERE field = '994' AND sf = 'b' AND content = 'UCX'
)
SELECT i.id AS instance_id
FROM folio_inventory.instance AS i
JOIN field_998 AS r1 ON i.id = r1.instance_id
LEFT JOIN field_994 AS r2 ON r1.srs_id = r2.srs_id
WHERE r2.srs_id IS NULL AND (i.creation_date >= '2023-01-27' AND i.creation_date < '2023-02-01');
