### ISSUE TITLE
Incorrect Text in URL Field 

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#49]
- [ ] Create Wiki Page for Report
- [x] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [x] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

856 z contains "Request"

If I get reports (or see usage) of broken links with electronic resources, I want to see if there's a pattern or if it is just a one-time issue. In this example, I want to catch links that say things like "Request Item from Stanford" that were accidentally loaded with our MARC

**Comment by blocke1** [comment]
Search string in Sierra:

856 z contains "Request"

**Comment by steveellis** [comment]
Related #55.

**Comment by blocke1** [comment]
RDF:
https://docs.google.com/document/d/1U8ZRjJKhRkWkCgZ4GQ-HQxLBYQEac9q-eiK9KgO-b7s/edit#heading=h.nl0qi6isouoc

**Comment by blocke1** [comment]
Report example: 
[Incorrect Text in URL Field ](https://docs.google.com/document/d/1a7-1GsfhYh3moTjzIYxC3Fh5HziGrSoh/edit)
