### ISSUE TITLE
Overdue Items

### ISSUE THREAD

**Issue by steveellis** [culibraries/library-reporting#53]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

Wiki Page: [Overdue Items](./Overdue-items)

@curtdwilliams Do we need this report? There's one in FA:

https://github.com/folio-org/folio-analytics/tree/main/sql/report_queries/overdue_items

**Comment by steveellis** [comment]
@curtdwilliams We're hoping you can provide some feedback on this report. Is this something we need? If so I would imagine that all of the fields that are in the report linked above are available in the LDP app (the UI to LDP in folio).

**Comment by curtdwilliams** [comment]
We will need this report and it appears that the LDP app provides the proper output.

**Comment by arthur-aguilera** [comment]
Not currently needed. System sends automated notes to the patron.

**Comment by arthur-aguilera** [comment]
Not currently needed. System sends automated notes to the patron. Real needs are captured in the Coming Billed report
