### ISSUE TITLE
Loans by Location

### ISSUE THREAD

**Issue by steveellis** [culibraries/library-reporting#54]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

Do we need this? Just noticing it in FOLIO analytics.

**Comment by katallm** [comment]
> Do we need this? Just noticing it in FOLIO analytics.

I can check out whether it's covered and take a different report if we don't need this! Otherwise I'll give this report a go.

**Comment by arthur-aguilera** [comment]
@steveellis Are you referring to the Pick list report? https://github.com/folio-org/folio-analytics/tree/main/sql/report_queries/pick_list

**Comment by steveellis** [comment]
@arthur-aguilera I should have linked to it but I'm pretty sure a report called that would have been there by that name. Maybe something got renamed.

**Comment by sabetiv** [comment]
Look at Cornell's CR100 report https://github.com/cul-it/cul-folio-analytics/tree/main/canned_reports/CR100
