### ISSUE TITLE
Figure out how to query MARC fields directly

### ISSUE THREAD

**Issue by steveellis** [culibraries/library-reporting#55]
Looking through our tickets some (not all) of our reports would like to be able to query certain MARC fields directly. It's not immediately clear how to go about this in LDP or MetaDb, but _if we could figure that out_ we'd be a lot closer to getting a grip on some of our reports.

**Comment by blocke1** [comment]
I haven't been able to look in depth at this, but this Wiki page might be able to help us with this!
https://wiki.folio.org/display/FOLIOtips/MARC+Mappings+Information

**Comment by steveellis** [comment]
It is possible to search MARC fields directly via the FOLIO API as documented [here](https://wiki.folio.org/display/FOLIOtips/MARC+Search+Query+API).

**Comment by steveellis** [comment]
In LDP 1.x there is a table called `srs_marctab` which has a column for the MARC numerical field and a way to map that back to the instance and SRS record. So using this we can query on the contents of a MARC field and do a join to get whatever else we want regarding the instance.

![Snip20220418_9](https://user-images.githubusercontent.com/104455/163868686-cf0ce66a-f87a-4a84-9782-0c93c44d1725.png)
