### ISSUE TITLE
Liaison Requests Report on Materials they Need - Vague Request

### ISSUE THREAD

**Issue by ahlisbon** [culibraries/library-reporting#56]
- [ ] Create Wiki Page for Report
- [ ] Add Wiki Page to [Current Reports Directory](https://github.com/culibraries/library-reporting/wiki/Current-Reports)
- [ ] Identify Fields Needed for Report
- [ ] Check [FOLIO Analytics](https://github.com/folio-org/folio-analytics) for exisiting reports or tables
- [ ] Check [Cornell's Reports](https://confluence.cornell.edu/display/folioreporting/FOLIO+Canned+Reports+Directory#FOLIOCannedReportsDirectory-CollectionDevelopmentReports) for exisiting reports or tables
- [ ] Build Query
- [ ] Query Needs Reviewed
- [ ] Add Query + ReadMe to Library Report github
- [ ] Update Wiki with "How to Run"

I need to know everything we own related to education in Africa.

**Comment by ahlisbon** [comment]
Expect vague requests like this one. Priority one is how broad or not is the request? For example, is there a range of dates that is actually needed? Very likely for a request like this, that is very "subject" or "topic" driven, the Liaison will need to provide a set of Subject Headings and/or key words to help identify such materials. Further, are things that need to absolutely NOT be included?

It's also important to know what the goal of the report is? What question is the liaison actually trying to answer? Are they helping show a faculty member what the extent of the subject matter is? Are they doing a grant? Are they providing annual statistics to a professional organization?

The answer can address whether an in app report, LDP report, standard query, or custom query is needed. What fields would be needed in the export in order for the question to be answered? Examples could be number of checkouts, titles, formats, etc.

Look at Report Definition/RDF spec.

**Comment by arthur-aguilera** [comment]
Possibly covered by Title_Count report - may need to modify: https://github.com/folio-org/folio-analytics/tree/main/sql/report_queries/title_count

**Comment by arthur-aguilera** [comment]
Replaced by #77
