### ISSUE TITLE
Link to various mapping docs docs in the wiki

### ISSUE THREAD

**Issue by steveellis** [culibraries/library-reporting#61]
There are more than a few docs floating around there:

* https://docs.google.com/spreadsheets/d/1cKzZ4nt_vESqxObsnvdmOKdkPb041ZqMtbc2bXEkjmU/edit#gid=0
* https://docs.google.com/spreadsheets/d/1m_Cq_GmZX37gJPEjVWt9eOLXskUjSLUb-8KapWj0SIw/edit#gid=474441456
* https://docs.google.com/spreadsheets/d/19iP5hnUHqCuGMM5OQKdUWMNCT75ZK3EDa0Vx8LgUZ24/edit#gid=792519514

**Comment by steveellis** [comment]
Here's another one: https://docs.google.com/spreadsheets/d/1x-yT87CUJpNErJvbZ0lWREl1CghvyFOfA7jRZzyzBOw/edit#gid=1936558381.

**Comment by blocke1** [comment]
And another:

FOLIO Schema Parser:
https://docs.google.com/spreadsheets/d/1m_Cq_GmZX37gJPEjVWt9eOLXskUjSLUb-8KapWj0SIw/edit#gid=474441456

**Comment by steveellis** [comment]
https://github.com/culibraries/library-reporting/wiki#mapping-docs
