### ISSUE TITLE
Install and configure ldpmarc tool

### ISSUE THREAD

**Issue by arthur-aguilera** [culibraries/library-reporting#84]
The ldpmarc tool reads the SRS MARC data from the database tables public.srs_marc and public.srs_records. Next, it transforms only the current versions of the records from these tables into tabular data. The transformed records are written to the public.srs_marctab table.

https://docs.folio.org/docs/reporting/ldpmarc/

**Comment by arthur-aguilera** [comment]
@blocke1 , @sabetiv @erikradio I can't tell if every person will have to download this tool, or if this is something that we could set up through Core Applications & Technology? Maybe a few of us can download it and get trained on how to use it?

**Comment by blocke1** [comment]
@arthur-aguilera ​I do not understand much of any of those “building” instructions.​ It seems like a lot more than simply downloading an add on.​ ​We'll definitely need the ability to query MARC fields for catalog management queries though, so we do need to get this addition to the LDP. Arthur, I saw your comment in slack. I tried accessing the public.srs_marctab table as well and was also denied permission. I'll ask Index Data to give us permissions and also if they have anyone with experience with Ldpmarc who can maybe help us figure this out. I'll let you all know what I find out.

**Comment by blocke1** [comment]
Per John Malconian at Index Data "the schema/tables you are looking for in Metadb for transformed MARC records are folio_source_record.marctab and folio_source_record.marc__t.   The public schema is a relic of LDP v1 and LDPMarc. "

We do not need to install/build ldpmarc as the marc transformation is taken care of in those tables. 

Also per Nassib: marctab but is about to change to marc__t in Metadb v1.0.5 to improve consistency of naming: 
https://d1f3dtrg62pav.cloudfront.net/doc/#_marc_transformation

**Comment by blocke1** [comment]
@arthur-aguilera I think we can close this issue?

**Comment by arthur-aguilera** [comment]
Built into metadb! Thanks, @blocke1 for figuring this out for us!
